# Project scaffolding ---------------------------------------------------------

#' Create the standard project directory skeleton
#'
#' Idempotent. Creates `code/`, `data/`, `output/`, `docs/`, and `tests/`
#' subtrees under `path` (only those requested), each with a `.gitkeep` marker,
#' and ensures `scratch/` is git-ignored.
#'
#' @param path Project root (default current directory).
#' @param code,data,output,docs,tests Logical; create that subtree.
#' @param extra Optional character vector of additional relative dirs to create.
#' @return `path`, invisibly.
#' @export
make_file_dirs <- function(path = ".", code = TRUE, data = TRUE, output = TRUE,
                           docs = TRUE, tests = TRUE, extra = NULL) {
  subtrees <- c(
    if (code)   c("code/functions", "code/analysis"),
    if (data)   c("data/raw", "data/processed", "data/metadata"),
    if (output) c("output/tables", "output/figures", "output/models"),
    if (docs)   "docs",
    if (tests)  "tests/testthat",
    extra
  )
  for (d in subtrees) {
    abs <- fs::path(path, d)
    fs::dir_create(abs)
    keep <- fs::path(abs, ".gitkeep")
    if (!fs::file_exists(keep)) fs::file_create(keep)
  }
  .ensure_gitignore_entry(path, "scratch/")
  fs::dir_create(fs::path(path, "scratch"))
  invisible(path)
}

#' Scaffold a new research project
#'
#' Creates a project of one of two archetypes:
#' * `"analysis"` - builds the `code/` + `data/` + `output/` skeleton via
#'   [make_file_dirs()] and writes the project mechanics directly (a PHI-aware
#'   `.gitignore`, an `renv`-activation `.Rprofile`, `<name>.Rproj`, a README
#'   stub, the `memos/` + `workflow-feedback.md` state stack, and an optional
#'   `targets` pipeline stub). It writes **no** `CLAUDE.md` and **no** `.claude/`:
#'   the router is generated by the `project-setup` skill and the safety hooks
#'   live in the installed kernel (`~/.claude/`), so a per-project copy would only
#'   drift. PHI protection that must travel with the repo lives in the
#'   `.gitignore` (raw/derived data and data extensions are ignored).
#' * `"package"` - wraps [usethis::create_package()] and layers the package
#'   best-practices set (MIT license, testthat 3, roxygen markdown, pkgdown,
#'   R-CMD-check + coverage + pkgdown GitHub Actions, NEWS, self-contained
#'   `.claude/`).
#'
#' @param name Project name (also the new directory name).
#' @param path Parent directory in which to create the project (default ".").
#' @param type `"analysis"` or `"package"`.
#' @param targets Logical; for analysis projects, scaffold a `_targets.R` stub.
#' @param git Logical; initialise a fresh git repository (default `TRUE`).
#' @return The created project path, invisibly.
#' @seealso The `project-setup` skill (biostat marketplace), which calls this to
#'   scaffold mechanics and then generates the project router.
#' @export
create_project <- function(name, path = ".", type = c("analysis", "package"),
                           targets = FALSE, git = TRUE) {
  type <- match.arg(type)
  dest <- fs::path(path, name)
  if (fs::dir_exists(dest) && length(fs::dir_ls(dest)) > 0L) {
    cli::cli_abort("{.path {dest}} already exists and is not empty.")
  }
  switch(
    type,
    analysis = .create_analysis_project(name, dest, targets, git),
    package  = .create_package_project(name, dest, git)
  )
  cli::cli_alert_success("Created {type} project at {.path {dest}}.")
  invisible(dest)
}

# --- internals ----------------------------------------------------------------

.create_analysis_project <- function(name, dest, targets, git) {
  make_file_dirs(dest) # code/ data/ output/ docs/ tests/ skeleton + scratch/
  .write_analysis_gitignore(dest) # PHI-aware; overwrites the scratch-only stub
  .write_rprofile(dest)
  .write_rproj(dest, name)
  .write_analysis_readme(dest, name)
  .write_state_stack(dest)
  if (isTRUE(targets)) .write_targets_stub(dest)
  if (isTRUE(git)) .git_init(dest)
}

.create_package_project <- function(name, dest, git) {
  usethis::create_package(dest, open = FALSE, rstudio = FALSE)
  usethis::with_project(dest, quiet = TRUE, code = {
    .try("MIT license",      usethis::use_mit_license("David Chen"))
    .try("roxygen markdown", usethis::use_roxygen_md())
    .try("testthat 3",       usethis::use_testthat(3))
    .try("package doc",      usethis::use_package_doc())
    .try("NEWS",             usethis::use_news_md())
    .try("readme",           usethis::use_readme_md())
    .try("pkgdown",          usethis::use_pkgdown())
    .try("R-CMD-check CI",   usethis::use_github_action("check-standard"))
    .try("coverage CI",      usethis::use_github_action("test-coverage"))
    .try("pkgdown CI",       usethis::use_github_action("pkgdown"))
  })
  .write_air_toml(dest)
  .write_claude_package(dest)
  if (isTRUE(git)) .git_init(dest)
}

.try <- function(label, expr) {
  tryCatch(force(expr), error = function(e) {
    cli::cli_alert_warning("Skipped {label}: {conditionMessage(e)}")
  })
}

#' @keywords internal
#' @noRd
.write_state_stack <- function(dest) {
  # Directory + pure-mechanical stub only. The *content* templates
  # (memos/decisions.md seed, PROJECT.md) are biostat-owned and dropped in by
  # the project-setup skill — one home per fact, not duplicated here.
  memos <- fs::path(dest, "memos")
  fs::dir_create(memos)
  keep <- fs::path(memos, ".gitkeep")
  if (!fs::file_exists(keep)) fs::file_create(keep)
  writeLines(c(
    "# Workflow feedback",
    "",
    "**Tooling friction only** - harness quirks, plugin/command mechanics, CI",
    "problems. Kept distinct from `memos/decisions.md` (decisions) and any",
    "output-quality log.",
    "",
    "Format: `YYYY-MM-DD - <tool> - friction -> action`",
    "",
    "---"
  ), fs::path(dest, "workflow-feedback.md"))
}

.write_rprofile <- function(dest) {
  writeLines(c(
    "# renv activation - guarded so the project loads cleanly *before*",
    "# renv::init() has been run.",
    "if (file.exists(\"renv/activate.R\")) source(\"renv/activate.R\")"
  ), fs::path(dest, ".Rprofile"))
}

.write_rproj <- function(dest, name) {
  writeLines(c(
    "Version: 1.0",
    "",
    "RestoreWorkspace: No",
    "SaveWorkspace: No",
    "AlwaysSaveHistory: No",
    "",
    "EnableCodeIndexing: Yes",
    "UseSpacesForTab: Yes",
    "NumSpacesForTab: 2",
    "Encoding: UTF-8",
    "",
    "RnwWeave: knitr",
    "LaTeX: XeLaTeX"
  ), fs::path(dest, paste0(name, ".Rproj")))
}

.write_analysis_readme <- function(dest, name) {
  writeLines(c(
    paste0("# ", name),
    "",
    "{{ONE-LINE description of the project.}}",
    "",
    "## Layout",
    "",
    "```",
    "code/functions/   pure, documented, reusable functions (no library() calls)",
    "code/analysis/    scripts or _targets.R that orchestrate the functions",
    "data/raw/         read-only raw inputs (git-ignored - PHI)",
    "data/processed/   derived analysis datasets (git-ignored); processed means it went",
    "                   through some pipeline step, NOT that it is de-identified",
    "data/metadata/    curated, VERIFIED non-sensitive codebooks / dictionaries (versioned)",
    "output/           tables, figures, models (git-ignored; markers kept)",
    "docs/             rendered deliverables (reports, slides) - versioned",
    "tests/testthat/   tests, run with testthat::test_dir(\"tests/testthat\")",
    "```",
    "",
    "## Reproducibility",
    "",
    "Dependencies are pinned with [`renv`](https://rstudio.github.io/renv/):",
    "`renv::init()` to start, `renv::restore()` after cloning.",
    "",
    "## PHI constraint",
    "",
    "Never commit, print, or transmit individual-level patient data. `data/raw/`",
    "and `data/processed/` are git-ignored. `data/processed/` is not automatically",
    "de-identified just because it has been processed - verify before treating it",
    "as safe. Suppress table cells with counts below the project's threshold before",
    "any output leaves the project."
  ), fs::path(dest, "README.md"))
}

.write_analysis_gitignore <- function(dest) {
  writeLines(c(
    "# --- R ---",
    ".Rproj.user/",
    ".Rhistory",
    ".RData",
    ".Ruserdata",
    "*-Ex.R",
    "/*.tar.gz",
    "/*.Rcheck/",
    "",
    "# --- Quarto / RMarkdown ---",
    "/.quarto/",
    "*_cache/",
    "*_files/",
    "*.knit.md",
    "*.utf8.md",
    "",
    "# --- Python ---",
    "__pycache__/",
    "*.py[cod]",
    ".ipynb_checkpoints/",
    ".venv/",
    "venv/",
    "",
    "# --- renv (commit renv.lock + renv/activate.R + renv/settings.json only) ---",
    "renv/library/",
    "renv/local/",
    "renv/cellar/",
    "renv/staging/",
    "renv/python/",
    "",
    "# --- targets ---",
    "_targets/",
    "",
    "# --- scratch (throwaway working files) ---",
    "scratch/",
    "",
    "# --- OS ---",
    ".DS_Store",
    "Thumbs.db",
    "*.swp",
    "*~",
    "",
    "# --- Data: NEVER commit individual-level data (PHI) ---",
    "data/raw/*",
    "data/processed/*",
    "!data/raw/.gitkeep",
    "!data/processed/.gitkeep",
    "*.rds",
    "*.RData",
    "*.rda",
    "*.qs",
    "*.qs2",
    "*.parquet",
    "*.feather",
    "*.sas7bdat",
    "*.dta",
    "*.xpt",
    "# Allow curated, non-PHI metadata (codebooks, variable dictionaries)",
    "!data/metadata/*.csv",
    "!data/metadata/*.xlsx",
    "!data/metadata/*.yml",
    "",
    "# --- Output: keep generated artifacts out of git; keep dir markers ---",
    "output/**/*",
    "!output/**/",
    "!output/**/.gitkeep",
    "# but DO version rendered deliverables placed under docs/",
    "!docs/**/*.pdf",
    "!docs/**/*.html",
    "!docs/**/*.docx",
    "",
    "# --- Logs / temp ---",
    "*.log",
    "*.tmp",
    "Rplots.pdf",
    "",
    "# --- Secrets / environment ---",
    ".Renviron",
    ".env",
    "*.key",
    "*.token",
    "*.secret",
    "credentials.*",
    "",
    "# --- Claude Code local (personal) overrides ---",
    ".claude/settings.local.json",
    "",
    "# --- Always keep .gitkeep markers ---",
    "!.gitkeep"
  ), fs::path(dest, ".gitignore"))
}

.write_targets_stub <- function(dest) {
  writeLines(c(
    "# _targets.R - pipeline definition. Run with targets::tar_make().",
    "library(targets)",
    "tar_source(\"code/functions\")",
    "tar_option_set(format = \"qs2\")",
    "",
    "list(",
    "  # tar_target(raw,   load_raw()),",
    "  # tar_target(clean, prepare(raw)),",
    "  # tar_target(fit,   analyze(clean))",
    ")"
  ), fs::path(dest, "_targets.R"))
}

.write_air_toml <- function(dest) {
  writeLines(c(
    "# Air formatter configuration (https://posit-dev.github.io/air/)",
    "[format]",
    "line-width = 80",
    "indent-width = 2"
  ), fs::path(dest, "air.toml"))
}

.write_claude_package <- function(dest) {
  cl <- fs::path(dest, ".claude")
  fs::dir_create(fs::path(cl, "hooks"))
  writeLines(c(
    "#!/usr/bin/env bash",
    "# Block direct pushes to main/master; encourage PR workflow.",
    "set -euo pipefail",
    "payload=\"$(cat)\"",
    "cmd=\"$(printf '%s' \"$payload\" | sed -n 's/.*\\\"command\\\"[[:space:]]*:[[:space:]]*\\\"\\(.*\\)\\\".*/\\1/p')\"",
    "case \"$cmd\" in",
    "  *\"git push\"*) printf '%s' \"$cmd\" | grep -qE '\\\\b(main|master)\\\\b' && { echo 'GUARD: push to main/master blocked; use a PR.' >&2; exit 2; } ;;",
    "esac",
    "exit 0"
  ), fs::path(cl, "hooks", "git-guard.sh"))
  fs::file_chmod(fs::path(cl, "hooks", "git-guard.sh"), "0755")
  writeLines(
    '{\n  "hooks": {\n    "PreToolUse": [\n      { "matcher": "Bash", "hooks": [ { "type": "command", "command": "bash .claude/hooks/git-guard.sh" } ] }\n    ]\n  }\n}',
    fs::path(cl, "settings.json")
  )
}

.ensure_gitignore_entry <- function(path, entry) {
  gi <- fs::path(path, ".gitignore")
  lines <- if (fs::file_exists(gi)) readLines(gi, warn = FALSE) else character(0)
  if (!any(grepl(entry, lines, fixed = TRUE))) {
    writeLines(c(lines, entry), gi)
  }
}

.git_init <- function(dest) {
  .try("git init", {
    gert::git_init(dest)
    gert::git_add(".", repo = dest)
    gert::git_commit("Initial project scaffold", repo = dest)
  })
}
